// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbOdBrdfVCIyH_X-gC9YFOBDzm6vbiwoI',
    appId: '1:169637009323:web:5c835a786bf304356e24ee',
    messagingSenderId: '169637009323',
    projectId: 'green-spy',
    authDomain: 'green-spy.firebaseapp.com',
    storageBucket: 'green-spy.firebasestorage.app',
    measurementId: 'G-QQ1EPK0C7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV5OEnxUEcj91hF3znlP3Vd9OT7xhKNBk',
    appId: '1:169637009323:android:7931b15322d882c66e24ee',
    messagingSenderId: '169637009323',
    projectId: 'green-spy',
    storageBucket: 'green-spy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPyUUF4gK0enHPjVqVfiN9z6koinYfw7o',
    appId: '1:169637009323:ios:f536e3c30e4b95b06e24ee',
    messagingSenderId: '169637009323',
    projectId: 'green-spy',
    storageBucket: 'green-spy.firebasestorage.app',
    iosBundleId: 'com.example.greenSpy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbOdBrdfVCIyH_X-gC9YFOBDzm6vbiwoI',
    appId: '1:169637009323:web:e6c9efa00274dc4c6e24ee',
    messagingSenderId: '169637009323',
    projectId: 'green-spy',
    authDomain: 'green-spy.firebaseapp.com',
    storageBucket: 'green-spy.firebasestorage.app',
    measurementId: 'G-JGMTKVLG2L',
  );
}
